version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  app:
    build: ./
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: ./
    env_file: .env
    command: celery -A app worker --loglevel=info
    depends_on:
      - redis
      - db
      - app
